---
title: "Making a comprehensive data frame"
author: "Lauren Whelton"
date: "2025-03-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "Visualizations of Raw Time Series Data"
output: html_document
---

```{r echo = T, results = 'hide'}
source("01_download_data.R")
```


```{r}
aquatics_targets |>
    ggplot(aes(x = datetime, y = observation)) +
      geom_point(size = .5) +
      facet_grid(variable~site_id, scales = "free_y") +
      theme_bw()
```


```{r}
weather_graph_labels <- c(`BARC` = "BARC",
                          `precipitation_flux` = "precipitation_flux",
                          `surface_downwelling_longwave_flux_in_air` = "longwave_flux",
                          `surface_downwelling_shortwave_flux_in_air` = "shortwave_flux")
historical_weather |>
    ggplot(aes(x = datetime, y = daily_mean)) +
      geom_point(size = .5) +
      facet_grid(variable~site_id,
                 scales = "free_y",
                 labeller = as_labeller(weather_graph_labels)) +
      theme_bw()
```


```{r}
weather_forecast |>
    ggplot(aes(x = datetime, y = daily_mean)) +
      geom_point(size = .5) +
      facet_grid(variable~site_id,
                 scales = "free_y",
                 labeller = as_labeller(weather_graph_labels)) +
      theme_bw()
```


```{r}
# Plotting pH values from 0-14
waq_filtered_clean <- waq_filtered |>
    filter(daily_pH >= 0, daily_pH <= 14)  # Remove outliers

waq_filtered_clean |>
    ggplot(aes(x = date, y = daily_pH)) +
      geom_point(color = "blue", size = .5) +
      facet_wrap(~siteID, scales = "free_y") +
      labs(title = "Daily pH Levels",
           x = "Date",
           y = "pH Value") +
      ylim(0, 14) +  # Set y-axis range
      theme_bw()
```

```{r}
# Plotting turbidity values
waq_filtered |>
    ggplot(aes(x = date, y = daily_turbidity)) +
      geom_point(color = "darkgreen", size = .5) +
      facet_wrap(~siteID, scales = "free_y") +
      labs(title = "Daily Turbidity Levels",
           x = "Date",
           y = "Turbidity (NTU)") +
      theme_bw()
```
```{r}
# Step 1: Pivot aquatics_targets to separate temperature, chla, and oxygen into their own columns
aquatics_targets_clean <- aquatics_targets %>%
  pivot_wider(
    names_from = variable,  # Use the variable.x column to create new columns
    values_from = observation # Use the observation column for the values
  )

# Step 2: Pivot historical_weather to separate precipitation_flux, longwave, and shortwave into their own columns
historical_weather_clean <- historical_weather %>%
  pivot_wider(
    names_from = variable,  # Use the variable.y column to create new columns
    values_from = daily_mean  # Use the daily.mean column for the values
  )

# Step 3: Merge aquatics_targets_clean, waq_filtered, and historical_weather_clean
merged_data <- aquatics_targets_clean %>%
  full_join(waq_filtered, by = c("datetime" = "date")) %>%
  full_join(historical_weather_clean, by = "datetime") %>%
  arrange(datetime)

# Step 4: Select and clean up the final columns
cleaned_data <- merged_data %>%
  select(
    datetime,
    oxygen,                     # From aquatics_targets
    chla,                       # From aquatics_targets
    daily_pH,                   # From waq_filtered
    daily_turbidity,            # From waq_filtered
    temperature,                # From aquatics_targets
    precipitation_flux,         # From historical_weather
    surface_downwelling_longwave_flux_in_air, # From historical_weather
    surface_downwelling_shortwave_flux_in_air # From historical_weather
  )

# View the cleaned data
print(cleaned_data)

# Optional: Save the cleaned data to a CSV file
# write.csv(cleaned_data, "cleaned_data.csv", row.names = FALSE)
```