---
title: "Visualizations of Raw Time Series Data"
output: html_document
---

```{r echo = T, results = 'hide'}
source("01_download_data.R")
```


```{r}
aquatics_targets |>
    ggplot(aes(x = datetime, y = observation)) +
      geom_point(size = .5) +
      facet_grid(variable~site_id, scales = "free_y") +
      theme_bw()
```


```{r}
weather_graph_labels <- c(`BARC` = "BARC",
                          `precipitation_flux` = "precipitation_flux",
                          `surface_downwelling_longwave_flux_in_air` = "longwave_flux",
                          `surface_downwelling_shortwave_flux_in_air` = "shortwave_flux")
historical_weather |>
    ggplot(aes(x = datetime, y = daily_mean)) +
      geom_point(size = .5) +
      facet_grid(variable~site_id,
                 scales = "free_y",
                 labeller = as_labeller(weather_graph_labels)) +
      theme_bw()
```


```{r}
weather_forecast |>
    ggplot(aes(x = datetime, y = daily_mean)) +
      geom_point(size = .5) +
      facet_grid(variable~site_id,
                 scales = "free_y",
                 labeller = as_labeller(weather_graph_labels)) +
      theme_bw()
```


```{r}
# Plotting pH values from 0-14
waq_filtered_clean <- waq_filtered |>
    filter(daily_pH >= 0, daily_pH <= 14)  # Remove outliers

waq_filtered_clean |>
    ggplot(aes(x = date, y = daily_pH)) +
      geom_point(color = "blue", size = .5) +
      facet_wrap(~siteID, scales = "free_y") +
      labs(title = "Daily pH Levels",
           x = "Date",
           y = "pH Value") +
      ylim(0, 14) +  # Set y-axis range
      theme_bw()
```

```{r}
# Plotting turbidity values
waq_filtered |>
    ggplot(aes(x = date, y = daily_turbidity)) +
      geom_point(color = "darkgreen", size = .5) +
      facet_wrap(~siteID, scales = "free_y") +
      labs(title = "Daily Turbidity Levels",
           x = "Date",
           y = "Turbidity (NTU)") +
      theme_bw()
```
